sudo: required
services:
  - docker

before_install:
  - docker build -t drlee123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success: 
  - docker build -t drlee123/multi-client ./client
  - docker build -t drlee123/multi-nginx ./nginx
  - docker build -t drlee123/multi-server ./server
  - docker build -t drlee123/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  #take to docker
  - docker push drlee123/multi-client
  - docker push drlee123/multi-nginx
  - docker push drlee123/multi-server
  - docker push drlee123/multi-worker



